# .scrutinizer.yml
checks:
    php: true

filter:
    paths: [ "src/*" ]
    excluded_paths:
        - "tests/*"
        - "*/vendor/*"

build:

    nodes:
        php56:
            environment:
                php: 5.6
        php71:
            environment:
                php: 7.1

    environment:
        timezone: UTC

    tests:
        override:
            -
                command: 'composer test'
                coverage:
                    file: 'code-coverage/coverage.xml'
                    format: 'clover'

    analysis:
        override:
            -
                command: phpcs-run
                use_website_config: true
